require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BusV3' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCPicker', :path => '../node_modules/@react-native-community/picker'

  pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

  pod 'react-native-ble-manager', :path => '../node_modules/react-native-ble-manager'

  target 'BusV3Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BusV3-tvOS' do
  # Pods for BusV3-tvOS

  target 'BusV3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
